services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src/html:/usr/share/nginx/html:ro
  ngrok:
        image: ngrok/ngrok:latest
        restart: unless-stopped
        depends_on:
          - nginx
        command:
          - "start"
          - "--all"
          - "--config"
          - "/etc/ngrok.yml"
        volumes:
          - ./ngrok.yml:/etc/ngrok.yml
        ports:
          - 4040:4040